name: manajemen_kost_by_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  shared_preferences: ^2.0.17
  mask_text_input_formatter: ^2.4.0
  firebase_core: ^2.5.0
  flutter_svg: ^2.0.0+1
  firebase_auth: ^4.2.6
  cloud_firestore: ^4.3.2
  octo_image: ^1.0.2
  cached_network_image: ^3.2.3
  get_cli: ^0.2.30
  image_picker: ^0.8.6+1
  firebase_storage: ^11.0.13
  collection: ^1.17.0

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

